# Generated by Django 2.1.1 on 2018-09-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=128)),
                ('domain', models.CharField(max_length=32)),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=255)),
                ('page_title', models.CharField(max_length=255)),
                ('edit_summary', models.CharField(max_length=800)),
                ('bot', models.BooleanField()),
                ('diff_id', models.PositiveIntegerField()),
            ],
        ),
    ]
