# Generated by Django 2.1.1 on 2018-09-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='bot',
        ),
    ]
