# Generated by Django 2.2 on 2021-01-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hashtags", "0005_auto_20200417_1019"),
    ]

    operations = [
        migrations.AddField(
            model_name="hashtag",
            name="has_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hashtag",
            name="has_video",
            field=models.BooleanField(default=False),
        ),
    ]
