# Generated by Django 2.2 on 2021-07-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hashtags", "0008_auto_20210713_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
